name: Build Image to ECR
description: A composite action to build image to ECR

inputs:
  aws-role-to-assume:
    description: AWS IAM Role for Github to assume
    required: true
  aws-region:
    description: AWS Region
    required: true
  aws-ecr-url:
    description: AWS ECR Repository url
    required: true
  docker-build-tag:
    description: Docker image tag
    required: true
  docker-build-args:
    description: Build args for 'docker build' command
    required: true
    default: ''
  docker-build-file-path:
    description: Dockerfile custom path
    required: true
    default: 'Dockerfile'

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role-to-assume }}

    - name: Login to ECR ${{ inputs.aws-ecr-url }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.aws-ecr-url }}

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.docker-build-context }}
        target: ${{ inputs.docker-build-target }}
        file: ${{ inputs.docker-build-file-path }}
        tags: |
          ${{ inputs.aws-ecr-url }}/${{ github.repository }}:latest
          ${{ inputs.aws-ecr-url }}/${{ github.repository }}:${{ inputs.docker-build-tag }}
        build-args: |
          ${{ inputs.docker-build-args }}
