name: Build Image to ECR
description: A composite action to build image to ECR

inputs:
  environment:
    description: Github Environment
    required: true
  docker-build-args:
    description: Build args for 'docker build' command
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_CREDS_ROLE_TO_ASSUME }}

    - name: Login to ECR ${{ vars.ECR_URL }}
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.ECR_URL }}

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.docker-build-context }}
        target: ${{ inputs.docker-build-target }}
        file: ${{ inputs.docker-file-path }}
        tags: |
          ${{ vars.ECR_URL }}/${{ github.repository }}:latest
          ${{ vars.ECR_URL }}/${{ github.repository }}:${{ inputs.docker-tag }}
        build-args: |
          ${{ inputs.docker-build-args }}
