name: Build and deploy workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      environment:
        required: true
        type: string
      docker-build-args:
        required: false
        type: string
        default: ''
      docker-tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: toketas/test-action/actions/build-image-to-ecr@main
        with:
          docker-build-args: ${{ inputs.docker-build-args }}
          docker-tag: ${{ inputs.docker-tag }}
