name: Build and deploy workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      environment:
        required: true
        type: string
      docker-build-args:
        required: false
        type: string
        default: ''
      docker-tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      contents: read
      id-token: write
      pull-requests: none

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: toketas/test-action/actions/build-image-to-ecr@main
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-ecr-url: ${{ vars.AWS_ECR_URL }}
          aws-role-to-assume: ${{ vars.AWS_CREDS_ROLE_TO_ASSUME }}
          docker-build-args: ${{ inputs.docker-build-args }}
          docker-build-tag: ${{ inputs.docker-tag }}
